//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent_Skills
    {
        public int Id_agent_skills { get; set; }
        public int Id_agent { get; set; }
        public int Id_skills { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Skills Skills { get; set; }
    }
}
