//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtReg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Agent_Skills> Agent_Skills { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Player_Agent> Player_Agent { get; set; }
        public virtual DbSet<Price_skills> Price_skills { get; set; }
        public virtual DbSet<Role_agent> Role_agent { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
    }
}
